

language: python
# command to install dependencies
dist: trusty
sudo: false

addons:
  chrome: stable

before_script:
- wget http://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.7/bin/
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start &
- sleep 3

install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest
