
language: python
# command to install dependencies

before_script:
- wget http://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.7/bin/
- export CHROME_BIN=chromium-browser

install:
  - pip install -r requirements.txt

# command to run tests

jobs:
  include:
    - name: auth
      addons:
        chrome: stable

        artifacts:
          debug: true
          paths:
            - $HOME/build/ulko81/project/reports/Report.html
          target_paths: test-auth/$(date +'%m-%d-%Y')
          s3_region: eu-west-1
      script:
      - pytest -v -m auth

    - name: seo
            addons:
              chrome: stable

              artifacts:
                debug: true
                paths:
                  - $HOME/build/ulko81/project/reports/Report.html
                target_paths: test-seo/$(date +'%m-%d-%Y')
                s3_region: eu-west-1
            script:
              - pytest -v -m seo
    - name: cart
        addons:
          chrome: stable

          artifacts:
            debug: true
            paths:
              - $HOME/build/ulko81/project/reports/Report.html
            target_paths: test-cart/$(date +'%m-%d-%Y')
            s3_region: eu-west-1
        script:
          - pytest -v -m cart
    - name: main
        addons:
          chrome: stable

          artifacts:
            debug: true
            paths:
              - $HOME/build/ulko81/project/reports/Report.html
            target_paths: test-main/$(date +'%m-%d-%Y')
            s3_region: eu-west-1
        script:
          - pytest -v -m main
    - name: header
        addons:
          chrome: stable

          artifacts:
            debug: true
            paths:
              - $HOME/build/ulko81/project/reports/Report.html
            target_paths: test-header/$(date +'%m-%d-%Y')
            s3_region: eu-west-1
        script:
          - pytest -v -m header
 #- python hello.py




