

language: python
# command to install dependencies

addons:
  chrome: stable

before_script:
- wget http://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.7/bin/
- export CHROME_BIN=chromium-browser


install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest

after_script:
  - sudo apt update
  - sudo apt-get install sendmail
  - sudo apt-get install mutt
  - echo 'Travis Report' | mutt -s 'Travis' zmeyko81@gmail.com -a /home/travis/build/ulko81/project/reports/Report.html

